blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/marvinpoo/gitstats/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/marvinpoo/gitstats/wiki
    about: Check our documentation for answers to common questions.